import { useEffect, useState } from "react";
export const useFetchProduct = (path?: string) => {};
export const useUpdateProduct = () => {};
export const useCreateProduct = () => {};
export const useDeleteProduct = () => {};
export const getCategory = () => {};
export const createCategory = () => {};
export const updateCategory = () => {};
export const getDeals = () => {};
export const updateDeals = () => {};
export const createDeals = () => {};
export const deleteDeals = () => {};
